export const MENU_ITEMS = [
  {
    id: '1',
    name: 'Chicken Crous\'t',
    description: 'Poulet mariné et pané maison, sauce secrète, riz blanc, oignons frits, sauce thaï, ciboulette.',
    priceMin: 6.50,
    priceMax: 9.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663473039589/ZduhfGfuDUikCLBWg6gRh6/dish-chicken-croustt-KtZAbMWgbpudqXGJobWbrH.webp',
    category: 'riz',
    badge: 'Bestseller',
  },
  {
    id: '2',
    name: 'Nems',
    description: 'Nems maison, légumes & viande ou crevettes, sauce piquante : l\'apéro crousti-crousti.',
    priceMin: 3.50,
    priceMax: 9.00,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663473039589/ZduhfGfuDUikCLBWg6gRh6/dish-nems-VqTvrT2K9bzFnSjyqQg3p8.webp',
    category: 'entrees',
    badge: null,
  },
  {
    id: '3',
    name: 'Orient Crous\'t',
    description: 'Viande hachée assaisonnée et cheddar fondu, sauce secrète, riz blanc, oignons frits, sauce thaï, ciboulette.',
    priceMin: 7.50,
    priceMax: 11.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663473039589/ZduhfGfuDUikCLBWg6gRh6/dish-orient-croustt-4NLkTgVuXDBKAhi8Ve5ngu.webp',
    category: 'riz',
    badge: 'Nouveau',
  },
  {
    id: '4',
    name: 'Nouilles Thai',
    description: 'Des nouilles sautées, des légumes croquants, un soupçon d\'épices thaï.',
    priceMin: 6.50,
    priceMax: 12.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663473039589/ZduhfGfuDUikCLBWg6gRh6/dish-nouilles-thai-fHfzfLhQG74hRbw37y6ZA6.webp',
    category: 'nouilles',
    badge: null,
  },
  {
    id: '5',
    name: 'Udon Thai',
    description: 'Des udon généreux, des légumes croquants, une sauce thaï pleine de peps.',
    priceMin: 6.50,
    priceMax: 12.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663473039589/ZduhfGfuDUikCLBWg6gRh6/dish-udon-thai-X3EBCs54pdug74kbDENXXD.webp',
    category: 'nouilles',
    badge: null,
  },
  {
    id: '6',
    name: 'Salade Crous\'t',
    description: 'Salade, poulet croustillant, nems poulet, riz, tomates cerises, carottes, olives, dés de fromage, sauce secrète, vinaigrette.',
    priceMin: 8.00,
    priceMax: 8.00,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663473039589/ZduhfGfuDUikCLBWg6gRh6/dish-salade-croustt-mJGGdtF4WuZ6RvswdYEiEC.webp',
    category: 'salades',
    badge: null,
  },
  {
    id: '7',
    name: 'Crevette Crous\'t',
    description: 'Duo de crevettes, sauce secrète, riz blanc, oignons frits, sauce thaï, ciboulette.',
    priceMin: 7.90,
    priceMax: 11.90,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663473039589/ZduhfGfuDUikCLBWg6gRh6/dish-crevette-croustt-jjPcLSCeK9aHxxmX4VhxqY.webp',
    category: 'riz',
    badge: null,
  },
];

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Sophie M.',
    rating: 5,
    comment: 'Une explosion de saveurs ! Le Chicken Crous\'t est absolument délicieux. La sauce secrète est incroyable. Je commande chaque semaine !',
    date: 'Mars 2025',
    avatar: '👩',
  },
  {
    id: '2',
    name: 'Thomas B.',
    rating: 5,
    comment: 'Le meilleur restaurant asiatique de Paris. Les nems sont croustillants à souhait et les portions sont généreuses. Livraison ultra rapide !',
    date: 'Février 2025',
    avatar: '👨',
  },
  {
    id: '3',
    name: 'Amira K.',
    rating: 5,
    comment: 'Crous\'t Wok c\'est une vraie découverte ! L\'Orient Crous\'t est mon coup de cœur. Entre la France et l\'Asie, c\'est vraiment une belle histoire d\'amour.',
    date: 'Janvier 2025',
    avatar: '👩',
  },
  {
    id: '4',
    name: 'Lucas D.',
    rating: 5,
    comment: 'Qualité irréprochable, service rapide et personnel adorable. Les Nouilles Thai sont parfaites, bien épicées comme il faut. Bravo à toute l\'équipe !',
    date: 'Mars 2025',
    avatar: '👨',
  },
  {
    id: '5',
    name: 'Chloé R.',
    rating: 5,
    comment: 'La Salade Crous\'t est fraîche et gourmande à la fois. Je n\'aurais jamais pensé qu\'une salade pouvait être aussi satisfaisante. Incontournable !',
    date: 'Février 2025',
    avatar: '👩',
  },
];

export const FAQ_ITEMS = [
  {
    id: '1',
    question: 'Quels sont vos horaires d\'ouverture ?',
    answer: 'Nous sommes ouverts 7 jours sur 7, de 11h à 22h30. Commandez en ligne à tout moment !',
  },
  {
    id: '2',
    question: 'Livrez-vous à domicile ?',
    answer: 'Oui ! Nous livrons gratuitement dans un rayon de 3 km à partir de 20€ de commande. La livraison est garantie en 30 minutes.',
  },
  {
    id: '3',
    question: 'Peut-on personnaliser les plats ?',
    answer: 'Absolument ! Chez Crous\'t Wok, la personnalisation est au cœur de notre concept. Indiquez vos préférences lors de la commande (niveau de piment, sans oignons, etc.).',
  },
  {
    id: '4',
    question: 'Proposez-vous des options végétariennes ?',
    answer: 'Oui, plusieurs de nos plats peuvent être adaptés en version végétarienne. Contactez-nous pour plus d\'informations.',
  },
  {
    id: '5',
    question: 'Comment puis-je passer une commande ?',
    answer: 'Vous pouvez commander directement via notre application, par téléphone au +33 667 155 358, ou en vous rendant au restaurant au 78 Avenue des Champs Élysées, Paris.',
  },
  {
    id: '6',
    question: 'Qu\'est-ce que la sauce secrète ?',
    answer: 'Notre sauce secrète est une recette maison onctueuse et crémeuse, préparée chaque jour avec des ingrédients frais. Sa composition exacte reste... secrète ! 😄',
  },
];

export const COMMITMENTS = [
  { id: '1', icon: 'clock.fill', title: 'Service 7/7', description: 'Ouvert tous les jours pour vous servir' },
  { id: '2', icon: 'leaf.fill', title: 'Cuisine propre', description: 'Hygiène irréprochable garantie' },
  { id: '3', icon: 'map.fill', title: 'Lieu organisé', description: 'Espace de restauration agréable' },
  { id: '4', icon: 'sparkles', title: 'Super Chefs', description: 'Cuisiniers passionnés et expérimentés' },
  { id: '5', icon: 'star.fill', title: 'Qualité irréprochable', description: 'Ingrédients frais sélectionnés' },
  { id: '6', icon: 'speedometer', title: 'Rapidité', description: 'Livraison en 30 minutes' },
  { id: '7', icon: 'hand.thumbsup.fill', title: 'Personnalisation', description: 'Plats adaptés à vos goûts' },
];
